[project]
name = "proofreading"
version = "0.1.0"
description = "a TUI written in python for powerful proofreading actions in adobe reader (windows-only)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyautogui>=0.9.54",
    "pyperclip>=1.11.0",
    "pytest>=9.0.0",
    "windows-curses>=2.4.1",
]

[project.scripts]
proofread = "proofreading.__main__:main"

[tool.uv]
package = true

[tool.uv.build-backend]
module-root = "src"

[tool.ruff.lint]
ignore = [ "F401", "F403"]

